---
- name: Install nginx
  hosts: web1


  tasks:

  - name: Install nginx
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
       - wget
       - nginx
       - gcc
       - vim
       - curl
       

  - name: Insert Index Page
    template:
      src: index.html
      dest: /usr/share/nginx/html/index.html

  - name: Start NGiNX
    service:
      name: nginx
      state: started

  - name: cmd for ip
    command: ifconfig
    register: cat
  - debug: var=cat.stdout_lines
